# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Carpentry for Biologists
description:      'Teaching the tools to get computers to do cool science'
url:              http://github.com/tychen742/semester-biology
baseurl:          /semester-biology
email:            datacarpentrysemester@weecology.org
feedbackurl:      docs.google.com/forms/d/1y35uJukuZ9MPKQWWqw0Y8R4VOiaOtFJezDY_t_kJfTs/
author:
  name:           'Ethan White'
  url:            https://twitter.com/ethanwhite

github:
  repo:           https://github.com/tychen742/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'
