# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Introduction to Data Science
description:      'How to think like a data scientist'
url:              https://tychen742.github.io/datascience
baseurl:          /datascience
email:            
feedbackurl:      docs.google.com
author:
  name:           'TY Chen' 
  url:            http://tychen.us/

github:
  repo:           https://github.com/tychen742/datascience
  #               Be sure the 'Issues' feature is activated in 'Settings'
