# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Science w/ R
description:      'How to think like a data scientist'
url:              https://datascience.tychen.us/
baseurl:          
email:            
feedbackurl:      docs.google.com
author:
  name:           'TY Chen' 
  url:            https://datascience.tychen.us/

github:
  repo:           https://github.com/tychen742/datascience
  #               Be sure the 'Issues' feature is activated in 'Settings'
# theme:            minima

theme: jekyll-theme-minimal